### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by pingufreak** [raspberrypi/picoprobe#42]
Flashing an elf through gdb takes aproximately 2 minutes, which is too long compared to the Raspberry Pi 4 SWD or Blackmagic Probe flashing. Is there any improvement ongoing? Also to use PIOs for faster flashing? Thx

**Comment by lurch** [comment]
You might want to have a look at #31 ?

**Comment by flaviut** [comment]
Following up here as well @lurch, but #31 does not provide any performance improvement until the message queue is lengthened from 2 to 255. Additional details in the patch here: https://github.com/raspberrypi/picoprobe/pull/31#issuecomment-1295517910

This is because a short message queue runs against USB's minimum 2ms latency, which at 8 bytes/roundtrip is very slow.

**Comment by P33M** [comment]
Please quantify "speed".
